extends Node

signal game_started
signal game_finished(victory: bool)
signal enemy_spawned(enemy: Enemy)
signal enemy_died(enemy_data: EnemyData, position: Vector2, experience_value: float)
signal boss_warning_started(boss_data: EnemyData, spawn_position: Vector2)
signal boss_spawned(enemy: Enemy)
signal boss_defeated(enemy_data: EnemyData)
signal experience_changed(current: float, required: float)
signal player_leveled_up(new_level: int)
signal upgrade_selected(title: String)
signal formation_equipped(column_index: int, formation_data: TowerFormationData)
signal tower_type_activated(tower_id: StringName)
signal tower_type_upgraded(tower_id: StringName, level: int)
signal tower_branch_selected(tower_id: StringName, branch_id: StringName)
signal tower_final_upgrade_reached(tower_id: StringName, branch_id: StringName)
signal core_level_changed(level: int)
signal core_branch_selected(branch_id: StringName)
signal cursor_level_changed(level: int)
signal cursor_branch_selected(branch_id: StringName)
signal tower_disabled(column_index: int, duration: float)
signal target_cursor_moved(target_position: Vector2)
signal core_health_changed(current: float, maximum: float)
